module.exports.descriptors = [
    'Forest',
    'Garage',
    'Workout',
    'Park',
    'Cascade',
    'Cycling',
    'Italian',
    'Food',
    'Bullfrog',
    'Car',
    'Crazy',
    'Canada',
    'Maple',
    'Raptors',
    'Football',
    'Soccer',
    'Music',
    'Beach'
]

module.exports.places = [
    'Flats',
    'Village',
    'Activities',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Club',
    'Day',
    'Fundraiser',
    'Match',
    'Game',
    'Event',
    'Dance',
    'Sale',
    'Festival'
]